<a href="https://colab.research.google.com/github/anuragsingh472002/bis-lab-code/blob/main/parallel_cellular.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
from multiprocessing import Pool

def update_cell(args):
    grid, x, y = args
    neighbors = [
        grid[(x - 1) % grid.shape[0], (y - 1) % grid.shape[1]],
        grid[(x - 1) % grid.shape[0], y],
        grid[(x - 1) % grid.shape[0], (y + 1) % grid.shape[1]],
        grid[x, (y - 1) % grid.shape[1]],
        grid[x, (y + 1) % grid.shape[1]],
        grid[(x + 1) % grid.shape[0], (y - 1) % grid.shape[1]],
        grid[(x + 1) % grid.shape[0], y],
        grid[(x + 1) % grid.shape[0], (y + 1) % grid.shape[1]]
    ]
    alive_neighbors = sum(neighbors)

    if grid[x, y] == 1:  # Alive cell
        if alive_neighbors < 2 or alive_neighbors > 3:
            return 0  # Dies
        else:
            return 1  # Lives
    else:  # Dead cell
        if alive_neighbors == 3:
            return 1  # Becomes alive
        else:
            return 0  # Stays dead

def parallel_step(grid):
    with Pool() as pool:
        args = [(grid, x, y) for x in range(grid.shape[0]) for y in range(grid.shape[1])]
        results = pool.map(update_cell, args)

    new_grid = np.array(results).reshape(grid.shape)
    return new_grid

def run_simulation(grid, steps):
    for _ in range(steps):
        grid = parallel_step(grid)
    return grid

if __name__ == "__main__":
    # Example: Game of Life grid
    grid = np.array([
        [0, 1, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [1, 1, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]
    ])

    steps = 10
    print("Initial Grid:")
    print(grid)

    grid = run_simulation(grid, steps)

    print("Final Grid:")
    print(grid)


Initial Grid:
[[0 1 0 0 0]
 [0 0 1 0 0]
 [1 1 1 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
Final Grid:
[[0 0 0 1 1]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 1]
 [0 0 1 0 1]]
